#!/usr/bin/env bash
#Installs and configurates Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start
new_string="server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "/server_name _;/$new_string/" /etc/nginx/sites-available/default
service nginx restart
