#!/usr/bin/env bash
# This script displays I am invincible!!! when receiving a SIGTERM signal
trap "echo 'I am invincible!!!'" 15
i=1
while [ $i -gt 0 ]
do
	echo "To infinity and beyond"
	sleep 2
done
